name: ساخت APK از پروژه Godot

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip the project
        run: |
          mkdir godot_project
          unzip "into-the-fog-1.---.zip" -d godot_project

      - name: Export Godot APK
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: godot_project
          presets_to_export: Android

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Into-the-fog-1-APK
          path: godot_project/Into\ the\ fog\ 1.apk
